### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [bblodfon/femtoPowerControl#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info in Readme with Octave Version. Actual Version of Octave is 7.2.
if unknown, untested with octave, info about  this also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by bblodfon** [comment]
Hi, never tested this with Octave and don't plan to. 
This is very old code and with no guarantee, use it for inspiration only if you do something similar!

**Comment by stefano2734** [comment]
So you can make a notice in your readme with octave untested.
I am a newbie by octave with interest in FEM and CFD.
So you are the expert of your software. Can you make a test run for fun?
Here some last infos about octave.
https://wiki.octave.org/Differences_between_Octave_and_Matlab
https://wiki.octave.org/Release_History
https://octave.org/NEWS-7.html
